version: "3.9"
services:
  gentle:
    image: lowerquality/gentle
    ports:
      - 8765:8765
  app:
    build:
      context: .
    ports:
      - ${WEBSITE_PORT:-3001}:80
    volumes:
      - .:/app
  redis-host:
    image: redis:latest
    ports:
    - 6379:6379
  worker:
    build:
      context: .
      dockerfile: ./worker.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis-host
volumes:
  .:
